---

- name: install repo file for modern collectd on EL6
  template: src=gujops-collectd.repo.j2 dest=/etc/yum.repos.d/gujops-collectd.repo owner=root group=root mode=0644
  when: ansible_os_family == "RedHat"

- name: install collectd (EL)
  yum: name=collectd state=present
  when: ansible_os_family == "RedHat"

- name: write init file (EL)
  template: src=collectd.j2 dest=/etc/init.d/collectd owner=root group=root mode=0755
  notify: restart collectd
  when: ansible_os_family == "RedHat"

- name: write config file for collectd (non-debian)
  template: src=collectd.conf.j2 dest=/etc/collectd.conf validate='collectd -t -C %s' owner=root group=root mode=0644
  notify: restart collectd
  when: ansible_os_family != "Debian"