---

- name: install repo file for modern collectd on EL6
  template: src=gujops-collectd.repo.j2 dest=/etc/yum.repos.d/gujops-collectd.repo owner=root group=root mode=0644
  when: ansible_os_family == "RedHat"

- name: install collectd (EL)
  yum: name=collectd state=present
  when: ansible_os_family == "RedHat"

- name: install collectd (Debian)
  apt: name=collectd state=present
  when: ansible_os_family == "Debian"
  
- name: write config file for collectd (non-debian)
  template: src=collectd.conf.j2 dest=/etc/collectd.conf validate='collectd -t -C %s' owner=root group=root mode=0644
  notify: restart collectd
  when: ansible_os_family != "Debian"

- name: write config file for collectd (debian)
  template: src=collectd.conf.j2 dest=/etc/collectd/collectd.conf validate='/usr/sbin/collectd -t -C %s' owner=root group=root mode=0644
  notify: restart collectd
  when: ansible_os_family == "Debian"
  
- name: enable collectd service
  service: name=collectd state=started enabled=yes

- name: copy logrotate config
  template: src=collectd.logrotate.j2 dest=/etc/logrotate.d/collectd owner=root group=root mode=0644

- name: create /etc/collectd.d
  file: name=/etc/collectd.d state=directory owner=root group=root mode=0644

- name: create collectd.d placeholder conf file
  template: src=placeholder.conf dest=/etc/collectd.d/placeholder.conf owner=root group=root mode=0644


# write_graphite plugin

- name: write config for write_graphite plugin
  template: src=write_graphite.conf.j2 dest=/etc/collectd.d/write_graphite.conf validate='collectd -t -C %s' owner=root group=root mode=0644
  notify: restart collectd
  when: "'write_graphite' in {{ extra_plugins }}"

# MySQL plugin
  
- name: install mysql plugin
  yum: name=collectd-mysql state=present
  when: "'mysql' in {{ extra_plugins }}" and ansible_os_family == "RedHat"
  
- name: write config for collectd mysql plugin
  template: src=mysql.conf.j2 dest=/etc/collectd.d/mysql.conf validate='collectd -t -C %s' owner=root group=root mode=0644
  notify: restart collectd
  when: "'mysql' in {{ extra_plugins }}"

# memcache plugin

- name: install memcache plugin
  yum: name=collectd-memcachec state=present
  when: "'memcache' in {{ extra_plugins }}"

- name: write config for collectd memcache plugin
  template: src=memcache.conf.j2 dest=/etc/collectd.d/memcache.conf validate='collectd -t -C %s' owner=root group=root mode=0644
  notify: restart collectd
  when: "'memcache' in {{ extra_plugins }}"

# Varnish plugin

- name: install varnish plugin
  yum: name=collectd-varnish state=present
  when: "'varnish' in {{ extra_plugins }}"

- name: write config for varnish plugin
  template: src=varnish.conf.j2 dest=/etc/collectd.d/varnish.conf validate='collectd -t -C %s' owner=root group=root mode=0644
  notify: restart collectd
  when: "'varnish' in {{ extra_plugins }}"

# Nginx plugin

- name: install nginx plugin
  yum: name=collectd-nginx state=present
  when: "'nginx' in {{ extra_plugins }}"

- name: write config for nginx plugin
  template: src=nginx.conf.j2 dest=/etc/collectd.d/nginx.conf validate='collectd -t -C %s' owner=root group=root mode=0644
  notify: restart collectd
  when: "'nginx' in {{ extra_plugins }}"
