---

- include: "collectd_redhat.yml"
  when: ansible_os_family == "RedHat" 

- include: "collectd_debian_{{collectd_install}}.yml"
  when: ansible_os_family == "Debian"

- include: "collectd_common.yml"

- include: "plugins_redhat.yml"
  when: ansible_os_family == "RedHat" 

- include: "plugins_common.yml"