---
- name: plugins_common | write config for write_graphite plugin
  template: 
     src=write_graphite.conf.j2 
     dest="{{collectd_etc_plugins}}/write_graphite.conf"
     validate='collectd -t -C %s' 
     owner=root
     group=root 
     mode=0644
  notify: restart collectd
  when: "'write_graphite' in extra_plugins"

- name: plugins_common | write config for aggregation plugin
  template:
     src=aggregation.conf.j2
     dest="{{collectd_etc_plugins}}/aggregation.conf"
     validate='collectd -t -C %s'
     owner=root
     group=root
     mode=0644
  notify: restart collectd
  when: "'aggregation' in extra_plugins"
